class NotarySerializer < ActiveModel::Serializer
    attributes 	:id,
              :name,
              :email,
              :approved,
              :organizational_status,
              :phone,
              :identity_number,
              :gender,
              :dob,
              :privy_token,
              :privy_id,
              :privy_status,
              :lng,
              :lat,
              :address,
              :office_address,
              :komparisi,
              :occupation,
              :no_sk_notaris,
              :tgl_sk_notaris,
              :no_akta,
              :tgl_akta,
              :fax,
              :bank_account_notaris,
              :bank_name,
              :skmht_price,
              :apht_price,
              :fidusia_price

end
