# Privy
privy_api_registration_path: "registration"
privy_api_registration_status_path: "registration/status"
privy_api_upload_doc_path: "document/upload"
privy_api_check_doc_status_path: "document/status/{doc_token}"

# Cek Mutasi
cekmutasi_api_key: ""
cekmutasi_api_signature: ""
cekmutasi_api_baseurl: ""

cekmutasi_api_ovo_bank_list_url: "/ovo/transfer/bank-list"
cekmutasi_api_ovo_bank_inquiry_url: "/ovo/transfer/inquiry"
cekmutasi_api_ovo_bank_send_url: "/ovo/transfer/send"
cekmutasi_api_ovo_bank_detail_url: "/ovo/transfer/detail"

cekmutasi_api_ovo_inquiry_url: "/ovo/transfer-ovo/inquiry"
cekmutasi_api_ovo_send_url: "/ovo/transfer-ovo/send"